#pragma config(Motor,  motorC,          motorC,        tmotorNormal, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEMO_BUG 1

typedef struct
{
  int powerMotor;
} MOTOR_INFO;

MOTOR_INFO MotorInfo;

void RunMotor(MOTOR_INFO &motorInfo)
{
  int power = motorInfo.powerMotor;

#ifdef DEMO_BUG
  motor[motorC] = motorInfo.powerMotor;
#else
  motor[motorC] = power;
#endif
}

void CheckPower(MOTOR_INFO &motorInfo)
{
  debugPrintLine("Power=%d", motorInfo.powerMotor);
  if (motorInfo.powerMotor == -1)
  {
    debugPrintLine("Power is -1!");
  }
}   //CheckPower

task main()
{
  int i;

  while (true)
  {
    MotorInfo.powerMotor = -1;
    CheckPower(MotorInfo);
    for (i = 0; i <= 100; ++i)
    {
      MotorInfo.powerMotor = i;
      RunMotor(MotorInfo);
      wait1Msec(100);
    }
    for (i = 100; i >= 0; --i)
    {
      MotorInfo.powerMotor = i;
      RunMotor(MotorInfo);
      wait1Msec(100);
    }
    for (i = 0; i >= -100; --i)
    {
      MotorInfo.powerMotor = i;
      RunMotor(MotorInfo);
      wait1Msec(100);
    }
    for (i = -100; i <= 0; ++i)
    {
      MotorInfo.powerMotor = i;
      RunMotor(MotorInfo);
      wait1Msec(100);
    }
  }
}
