#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     lightRight,          sensorLightActive)
#pragma config(Sensor, S3,     lightCenter,         sensorLightActive)
#pragma config(Sensor, S4,     lightLeft,           sensorLightActive)
//#pragma config(Sensor, S4,     HTSmux,              sensorLowSpeed)
#pragma config(Motor,  motorA,          motorA,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorB,          motorB,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  motorC,          motorC,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorNormal, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#if 0
/// Copyright (c) Titan Robotics Club. All rights reserved.
///
/// <module name="hybrid.c" />
///
/// <summary>
///   This module is the main module for both autonomous and teleop modes.
/// </summary>
///
/// <remarks>
///   Environment: RobotC for Lego Mindstorms NXT.
/// </remarks>
#endif

#define HYBRID_MODE             1
#include "hotshot.h"

/// <summary>
///   This task is the program entry point.
/// </summary>
///
/// <returns> None. </returns>

task main()
{
  TraceInit(TRACE_MODULES, TRACE_LEVEL, MSG_LEVEL);
  DisplayInit();
  RobotInit();
  while (true)
  {
    InputTasks(true);
    MainTasks();
    OutputTasks();
    wait10Msec(1);
  }
}   //main
